FROM postgres:latest
ENV POSTGRES_DEFAULT_LOCALE=lv_LV
RUN localedef -i $POSTGRES_DEFAULT_LOCALE -c -f UTF-8 -A /usr/share/locale/locale.alias $POSTGRES_DEFAULT_LOCALE.UTF-8
ENV POSTGRES_INITDB_ARGS="--lc-collate=$POSTGRES_DEFAULT_LOCALE.utf8 --lc-ctype=$POSTGRES_DEFAULT_LOCALE.utf8"