FROM postgres:latest
ARG POSTGRES_DEFAULT_LOCALE=lv_LV
RUN localedef -i $POSTGRES_DEFAULT_LOCALE -c -f UTF-8 -A /usr/share/locale/locale.alias $POSTGRES_DEFAULT_LOCALE.UTF-8
ENV LANG $POSTGRES_DEFAULT_LOCALE.utf8